// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjWaXg4dwB064eZcSkh2vI_pCQVz72fU8',
    appId: '1:411144444263:web:6e5e980c3fcf5d7e2cf7c2',
    messagingSenderId: '411144444263',
    projectId: 'tareas-app-39031',
    authDomain: 'tareas-app-39031.firebaseapp.com',
    storageBucket: 'tareas-app-39031.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2AQbWUuBo6XNSE2z93vjkB7amgRn6nk',
    appId: '1:411144444263:android:47d406e4a2c9084a2cf7c2',
    messagingSenderId: '411144444263',
    projectId: 'tareas-app-39031',
    storageBucket: 'tareas-app-39031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6B8_p-6pWDfD7C1aVFFcuhmCIX05MN3I',
    appId: '1:411144444263:ios:9a138ff17f98a5a12cf7c2',
    messagingSenderId: '411144444263',
    projectId: 'tareas-app-39031',
    storageBucket: 'tareas-app-39031.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6B8_p-6pWDfD7C1aVFFcuhmCIX05MN3I',
    appId: '1:411144444263:ios:9a138ff17f98a5a12cf7c2',
    messagingSenderId: '411144444263',
    projectId: 'tareas-app-39031',
    storageBucket: 'tareas-app-39031.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjWaXg4dwB064eZcSkh2vI_pCQVz72fU8',
    appId: '1:411144444263:web:a2f7b42a37d213a62cf7c2',
    messagingSenderId: '411144444263',
    projectId: 'tareas-app-39031',
    authDomain: 'tareas-app-39031.firebaseapp.com',
    storageBucket: 'tareas-app-39031.firebasestorage.app',
  );
}
